[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
disallow_any_generics = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_calls = True
disallow_untyped_defs = True

plugins = 
    pydantic.mypy

[mypy-tests.*]
ignore_errors = False

[[mypy.overrides]]
module = "testcontainers.*"
ignore_missing_imports = True

[[mypy.overrides]]
module = "factory.*"
ignore_missing_imports = True

[[mypy.overrides]]
module = "vcr.*"
ignore_missing_imports = True
